#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" > /var/www/html/index.html
service nginx restart
