#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
utf allow 'Nginx HTTP'
sudo echo "Hello World!\n" > /var/www/html/index.nginx-debain.html

sudo service nginx restart
