#!/usr/bin/env bash
# Configure nginx HTTP response contains a custom header
sed -i '/index index.html index.htm index.nginx-debian.html/a \\tadd_header X-Served-By {$HOSTNAME;}' /etc/nginx/sites-available/default
service nginx reload 
