#!/usr/bin/env bash
# Configure nginx HTTP response contains a custom header
sed -i '/index index.html index.htm index.nginx-debian.html/a \\tadd_header X-Served-By '$HOSTNAME';\n \terror_page 404 /404.html;\n \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx reload
