#!/usr/bin/env bash
# Install load balancer

sudo apt-get update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg  /etc/haproxy/haproxy.cfg.copy

sudo printf %s '

fronted http
        bind :80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 1643-web-02 34.74.168.65:80 check
        server 1643-web-02 34.148.116.47:80 check
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
