#!/usr/bin/env bash
# display 'Best School' 10 times but for the 9th iteration that display 'Hi'
i=0
while ((i < 11));
do
	if ((i == 9));
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
