#!/usr/bin/env bash
#display 'Best School' 10 times but for the 4th iteration that display 'bad luck'
i=1
while [[ $i -le 10 ]];
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
